<?php

namespace App\Controllers;

class Test extends BaseController
{
    /**
     * Dislay list of match
     * @return view
     */
    public function index()
    {
        $datas = array();        

        echo view('innerpages/header');
        echo view('innerpages/menu');
        echo view('innerpages/top_header');
        echo view('test/test', $datas);
        echo view('innerpages/footer');
    }

    /**
     * Dislay list of match
     * @return view
     */
    public function test2()
    {
        $datas = array();        

        echo view('innerpages/header');
        echo view('innerpages/menu');
        echo view('innerpages/top_header');
        echo view('test/test2', $datas);
        echo view('innerpages/footer');
    }

    public function matching_club()
    {
        $clubs = [
            "Volley Ball Nantes",
            "Tours Volley-Ball",
            "Quimper Volley 29",
            "Nantes Rezé Métropole Volley",
            "Nice Volley-Ball",
            "Cambrai Volley",
            "Stade Poitevin Volley-Beach",
            "Evreux Volley-Ball",
            "Narbonne Volley",
            "AS Cannes Volley-Ball",
            "Paris Volley",
            "Puygouzon Castelnau Volley Ball",
            "Volley-Ball Bois d'Arcy",
            "Sete Volley-Ball Club",
            "Béziers Volley",
            "Montpellier-Volley UC",
            "AL Caudry Volley-Ball",
            "Stella Calais Volley",
            "Amiens Metropole Volley",
            "AS Sartrouville Volley-ball",
            "Draveil Volley Ball",
            "Sens Volley 89",
            "GFCA Volley-Ball",
            "Volley-Ball Arlésien",
            "Volley-Ball Pexinois Niort",
            "Genêts de Mesplède Volley",
            "Marseille Volley 13",
            "ASPTT Caen Volley",
            "ES Carpiquet Volley",
            "Volley Ball de Roncq",
            "Saint-Quentin Volley",
            "Nîmes Volley-Ball",
            "USM Malakoff Volley",
            "Chateaudun Volley-Ball",
            "ASCED Riaillé Volley Ball",
            "Volley Club de Valenciennes",
            "VB Mesanger",
            "USB Bouguenais Volley-Ball",
            "VB Famars",
            "Avignon Volley Ball",
            "IMT Mines Alès Volley",
            "Pontivy Volley-Ball",
            "Vannes Volley 56",
            "Touquet A.C. Volley-Ball & Beach",
            "Volley Club Mouvallois",
            "Harnes Volley-Ball",
            "ASER Volley-ball Rixheim",
            "Balez O Volley",
            "Volley Club Harnésien",
            "Maromme Canteleu Volley 76",
            "Grand Nancy Volley Ball",
            "Saint-Dié Volley-Ball",
            "Spacer's Toulouse Volley",
            "US Meyzieu Volley-Ball",
            "Martigues Volley-Ball",
            "Plessis-Robinson Volley Ball",
            "Clamart Volley",
            "Stade Montois Volley-ball",
            "Kloar-Aven VB 29",
            "SAS Volley Epinal",
            "ASPTT Mulhouse Volley-Ball",
            "Volley-Ball Romanais",
            "CASE Volley Saint-Etienne",
            "Luisant AC Volley",
            "Fréjus Var Volley",
            "Brocéliande Volley",
            "US Talence VB",
            "ASUL Lyon Volley",
            "Mende Volley Lozère",
            "Volley Club Hyères-Pierrefeu",
            "VB Villefranche Beaujolais",
            "Chaumont Volley-Ball 52 Haute-Marne",
            "Vandoeuvre Nancy Volley-Ball",
            "ASB Rezé Volley",
            "Arago de Sète VB",
            "St Herblain Volley Ball",
            "Bordeaux Mérignac Volley Les Burdis",
            "Municipal Olympique Mougins Volley-Ball",
            "Amicale Epernon Volley Ball",
            "Volley Club Saint Polois",
            "AS Landaise Volley ball",
            "Vincennes Volley Club",
            "Aubagne Carnoux Volley-Ball",
            "Asnieres Volley 92",
            "Volley-Ball la Rochette",
            "Joué Volley-Ball",
            "Salon Volley-Ball Club",
            "VB Torcy Marne la Vallee",
            "Institut fédéral de Volley-ball",
            "Tourcoing Lille Métropole Volley",
            "Agglo Sud Volley-Ball 76",
            "Saint-Renan Iroise Volley",
            "Maizieres Athletic Club Volley-Ball",
            "Beauvais Oise UC Volley",
            "Longueau Amiens Métropole VB",
            "CSSG Volley Ball Le Mans",
            "CA Brive/Correze Volley",
            "Levallois Sporting Club Volley",
            "Saint-Nazaire Volley-Ball Atlantique",
            "Volley-Ball Stade Laurentin",
            "LA Roche/Yon Volley-Ball",
            "Conflans Andrésy Jouy Volley-Ball",
            "CEP Poitiers/St Benoit VB",
            "Volley Club Chaunois",
            "Mtsangamouji Volley-Ball",
            "Union Volley-Ball Touraine",
            "AS Meudon Volley-Ball",
            "Volley-Ball Guerlédan",
            "Volley Club Tavaux",
            "Pornic Volley Ball",
            "Vitrolles Sports Volley-Ball",
            "ACH Volley LJUBLJANA (SLO)",
            "C Chartres Volley",
            "Vedène Volley Ball",
            "US Saint-Egrève Volley-Ball",
            "Noisy le Grand Volley-Ball",
            "Calcit Volley KAMNIK (SVN)",
            "Nouaillé Animation VB",
            "US Créteil Volley",
            "US Ivry Volley-ball",
            "Volley Biesheim",
            "Cercle Paul Bert Rennes Volley",
            "ASLJ Montpellier Croix d'Argent Volley-Ball",
            "Volley Club Pontarlier",
            "Moineau Volley Pei",
            "FLJEP Cuinchy - Volley-Ball",
            "JASCM VB",
            "SCUF Volley-Ball",
            "VSOP Ozoir Volley-Ball",
            "Adour Volley",
            "VB 14",
            "Istres Ouest Provence VB",
            "Pays d'Aix Venelles Volley-Ball",
            "Bayonne Volley-Ball",
            "UGS Thau Volley-Ball",
            "Ufolep 62 Volley-ball",
            "CSM Gennevilliers Volley-Ball",
            "Volley Ball Sarladais",
            "Leo Volley Détente",
            "Vero Volley MONZA (ITA)",
            "Volley Ball Grégorien",
            "Gien Volley",
            "Volley-Club de Feignies",
            "USV Vendôme Volley Ball",
            "Volley-Ball Club Appaméen",
            "Volley Haasrode LEUVEN (BEL)",
            "Saint-Raphaël Var Volley-Ball",
            "AS Montigny le Bretonneux Volley-Ball",
            "Volley Beaune",
            "Saint-Avé Volley-Ball",
            "Volley Villeneuve",
            "Volley Club M Tsapere",
            "VB Guichen",
            "Mouvement Volley Ball Lyssois",
            "SCM Chatillon Volley",
            "Reveil Sportif de Saint-Cyr Volley",
            "Volley Guémenéen",
            "Volley Kunheim",
            "BERLIN Recycling Volleys (GER)",
            "United Volleys FRANKFURT (GER)",
            "Volley Club de Tsingoni",
            "AS Volley Saint-Andre",
            "Volley Olympique de Sada",
            "SAM Mérignac Volley",
            "AS Pleumeleuc Bédée Volley-ball",
            "Volley-Ball Club de Vahibe",
            "Club Volley-Detente de Vendee",
            "UGS Pontivy Rohan Volley",
            "Agde Volley Ball",
            "Mauguio Volley Ball",
            "Volley-Ball des Greves",
            "Rocbaron Club Volley-Ball - Rcvb",
            "Volley-Ball de St Pierre",
            "Volley Ball Generac",
            "Volley-Ball Albigeois",
            "Grenade Volley Ball",
            "Cournon Volley-Ball",
            "US Cadalenoise VB",
            "Taupont Volley-Ball",
            "Volley Club Herouville",
            "Concarneau Volley",
            "Carcassonne Volley",
            "Comite Marie-Galantais VB",
            "Volley-Ball Club St-Leu",
            "Elorn Volleyball",
            "Volley-Ball Gruissan",
            "Luc Volley Club",
            "Alencon Volley",
            "Muret Volley-Ball",
            "Les 6 Volleyeurs Club Chiconi",
            "AS Volley-Ball de Tressange",
            "Union Sportive Ramonville VB",
            "Lons Volley-Club du Moulin",
            "SC Paray-Morangis Volley-Ball",
            "Goelo Cotes d'Armor Volley-Ball",
            "Mandelieu la Napoule VB",
            "Limours Volley-Ball",
            "Mazeres Cassagne Volley",
            "Volley Club Petite Foret",
            "LA Ligugeenne Volley-Ball",
            "Foug Volley Ball Club",
            "C Georges Brassens Volley-Ball",
            "Montmorency Volley Ball",
            "Crolles Volley Jeunes",
            "Montigny Volley 95",
            "Versailles Volley Ball",
            "Claira Salanque Volley-Ball",
            "Cisse Volley-Ball",
            "Esvres Volley-Ball",
            "AS Laxou Volley-Ball",
            "Coulommiers Volley-Ball",
            "Loches Volley-Ball",
            "Oya Volley-Ball",
            "Volley Club Clisson",
            "Volley Ball Halluin",
            "Volley Club Fontenaysien",
            "Intrepide Volley de Beaurepaire",
            "Volley Ball Club Wattignies",
            "ES Massy Volley",
            "US Lognes Volley-Ball",
            "Poissy Volley",
            "Laon Volley Ball",
            "Montgermont Volley-Ball Club",
            "AS Volley-Ball Velizy",
            "Orgerblon Volley-Ball",
            "AC Chapelain Volley",
            "ASM Belfort Volley-Ball",
            "Volley Club du Leff",
            "Corlay Volley-Ball Club",
            "Imana Volley",
            "Volley-Ball Ostwald",
            "Volley Club Vallon Causses",
            "Volley-Ball Hersinois",
            "Volley Club Liévin",
            "ASPTT Marmande Volley-Ball",
            "Vouille Volley Ball",
            "Montauban Volley-Ball 82",
            "Volley Balma Quint Fonsegrives",
            "Tarascon Foix VB",
            "Peyrins Volley-Ball",
            "Annemasse Volley 74",
            "Montelimar Volley",
            "Entente Forezienne Volley-Ball",
            "Saint Esteve Volley Ball",
            "Saintes Volley-Ball-Svb",
            "Cebazat Volley-Ball",
            "US Issoire Volley-Ball",
            "Vidauban Volley-Ball",
            "Volley Club Meximieux",
            "Ploemeur Volley",
            "Caen Volley-Ball",
            "Cognac Volley",
            "Eysines Volley-Ball",
            "Montamise Volley-Ball",
            "Volley-Ball Courcellois",
            "Autan Volley-Ball",
            "AS Hainnevillaise Volley",
            "Louviers Volley-Ball",
            "Castelnaudary VB",
            "Puylaurens Volley Ball",
            "Missillac Volley-Ball",
            "As. Volley Ouvert Privas",
            "Yaka Volley Via Venaissia",
            "Moirans Multi Volley-Ball",
            "Gap Volley-Ball",
            "Sainte Marie Volley Ball",
            "Volley Ball Carpentras",
            "AS Volley Ball Cergy",
            "Bussy Volley",
            "Morsang Volley",
            "Lunéville Volley-Ball",
            "Volley Club de Donnery",
            "Societe VB Franconville",
            "Ibos Volley",
            "Volley Club Marseillanais",
            "Volley Ball le Quesnoy",
            "Jonquieres Volley-Ball",
            "US Pontet Volley Avenir",
            "Monts Volley-Ball",
            "Lescar Promotion Volley-Ball",
            "Les Epesses Volley-Ball",
            "Argenteuil Volley Ball 95",
            "VB Club Ermont",
            "Aizenay Volley-Ball",
            "AS Volley du Garon",
            "Alas Ganil Volley Ball",
            "Reims Metropole Volley",
            "Rethel Club Volley-Ball",
            "Compiegne Volley",
            "Sable Volley-Ball",
            "Bourges Volley-Ball",
            "Volley Beaune Club",
            "Club Volley Loisirs Flandres",
            "Sympho Volley-Ball Treillieres",
            "Volley Club Chenôve",
            "Guingamp Volley-Ball",
            "Baie d'Armor Volley Ball",
            "Strasbourg Volley Ball",
            "Volley Sud Bassin d'Arcachon",
            "Dijon Talant Volley-Ball",
            "ASPTT Dijon Volley",
            "CAM Volley Epinal",
            "Volley-Ball Tulle Naves",
            "Avenir Fonsorbais Volley-Ball",
            "Volley Bron @ Lyon Lumiere",
            "Ambérieu Volley Ball",
            "Volley Club Talenconnais",
            "Gsd du Var de Volley-Ball",
            "UGS Pays des Rohan Volley",
            "GSD de Seine Maritime de Volley",
            "US Chambray lès Tours Volley",
            "US Carrières sur Seine Volley",
            "As.Sp.La Motte Volley",
            "Garches Vaucresson Volley-Ball",
            "ACSC Cormeilles Volley-Ball",
            "Vigneux Volley",
            "AC Longué Volley Ball",
            "Saint-Macaire Volley-Ball",
            "LA Christina Volley-Ball",
            "US Volley Dombes-Saone",
            "UGS Volley Sud Grenoblois",
            "Volley-Ball Club Toulousain",
            "Volley Club Mayotte 06",
            "Volley Club Wervicquois",
            "Beach Volley 83",
            "Ales Agglo Volley-Ball",
            "Volley du Kochersberg",
            "Montceau Volley Loisir",
            "Volley Club d'Orthe",
            "Volley-Ball Seichanais",
            "As.Sp. Camaret VB",
            "Canet 66 Volley-Ball",
            "Saint-Pierre Volley-Ball",
            "Volley Entente Guipel Aclc",
            "Bam Volleyball",
            "Volley 6 Paris",
            "Creusot Volley-Ball",
            "Colmarienne Volley",
            "Volley-Club Sarrebourg",
            "Volley-Ball Club Herrlisheim",
            "US Villeveyracoise VB",
            "Volley-Ball l'Huisserie",
            "Volley Club Maconnais",
            "Loos-Haubourdin Volley-Ball",
            "SMS Marquette VB",
            "Douai Volley-Ball",
            "Volley-Ball Club Cysoing",
            "Perpignan Roussillon VB",
            "AS Bondy Volley",
            "Club Volley Loisir 35",
            "Volley Club Jarrezien",
            "Cosmic Volley",
            "Roanne Riorges Volley-Ball",
            "Gsd 69 Volley",
            "Villers Cotterets Volley-Ball",
            "Volley Itancourtois Feminin",
            "Bavans Volley-Ball",
            "Biot Volley-Ball",
            "Volley Club Govennais",
            "Haute Vilaine Volley-Ball",
            "Fougeres Volley-Ball",
            "Plancoët Volley-Ball",
            "Volley Ball Club Malouin",
            "Vence Volley-Ball",
            "ES Blanquefort Volley",
            "AS SP VB Bergeracois",
            "Fidesienne Volley Ball",
            "Volley Ball Club Royan",
            "St Denis Olympique VB Reunion",
            "Suresnes Volley-Ball Club",
            "SMUC Marseille Volley-ball",
            "Volley-Club Nogentais",
            "Issy Volley",
            "Grandchamp Volley-Ball",
            "Besancon Volley-Ball",
            "Volley Club Mediterranee",
            "Lesquin Volley-Ball",
            "AS Moulins Volley-Ball",
            "Wittelsheim Volley-Ball",
            "Entrammes Volley-Ball",
            "AS Volley Paris_Asvp",
            "Arche Volley-Ball",
            "Fontaine Volley",
            "Volley-Ball Club Chaloupe",
            "Seclinoise Volley-Ball",
            "Niort Volley Ball",
            "Tomblaine Volley-Ball",
            "Volley Club de Remiremont",
            "Massalia Volley",
            "Oleron Volley Ball",
            "Volley-Club Vendrois",
            "Volley-Ball Pfastatt",
            "Volley Club Vieux Thann",
            "VB Club de Sierentz",
            "Volley-Ball Club Hirsingue",
            "Volley Loisirs Crevecoeur",
            "AS Volley Gigeanais",
            "Brece Sports Volley",
            "Lomme Volley-Ball",
            "AS Berck Volley-Ball",
            "Halluin Volley Metropole",
            "Chateau Thierry VB",
            "AS l'Union Volley-Ball",
            "Volley-Ball Club d'Ensisheim",
            "Saint-Lo Volley",
            "Paris Volley Club",
            "Volley-Club Plaisir-Villepreux",
            "Antony Volley",
            "Club Volley Detente 44",
            "Volley Club Sedanais",
            "Volley-Ball Rantigny-Liancourt",
            "Wasquehal Volley Ball",
            "CS Betton Volley-Ball",
            "Orvault Volley-Ball",
            "Volley Club du Lac",
            "Volley Loisir Sebastiennais",
            "Saint-Gély Volley-Ball",
            "Vias Volley-Ball",
            "Volley Olympique Mezois",
            "As. VB Nord Bassin",
            "VB Isneauville Bois-Guillaume",
            "Montanay Volley-Ball",
            "Gradignan Volley Club",
            "Firminy Volley-Ball",
            "Riom Volley-Ball",
            "Seyssins Volley",
            "Annecy Volley Ball",
            "Volley Loisir Gironde",
            "Marignane Volley-Ball",
            "Volley Pradetan Gardeen",
            "VB District Vichyssois",
            "Club Volley Detente Herault",
            "Beauchamp Volley-Ball",
            "Volley-Ball St-Mihiel",
            "Maen Roch Volley Ball",
            "Le Luc Volley Ball",
            "Volley-Ball Gaillon Aubevoye",
            "OSMS Sequedin Volley",
            "Mareuil Volley-Ball",
            "Volley Club Wissembourg",
            "Club Volley Detente 53",
            "Avenir Amboise Volley Ball",
            "AS Volley-Ball Sarreguemines",
            "Saint-Cyprien Volley-Ball",
            "As. Volley Osny Pontoise",
            "Club Volley-Ball Etampes",
            "Plessis Volley",
            "Challans Volley-Ball",
            "US Mulhouse Volley",
            "Le Cres Volley-Ball",
            "St-Jean Volley-Ball",
            "Volley-Ball Club Haguenau",
            "Volley-Ball Club Bailleulois",
            "Volley Ball Club Laferois",
            "LA Souffel Volley-Ball",
            "Vendrennes Volley-Ball",
            "Aurillac VB",
            "AS Villebon Volley-Ball",
            "Pantin Volley",
            "USM Gagny Volley",
            "VB Pouilly Saint-Nizier",
            "USM Montargis VB",
            "U.S.O Volley-Ball",
            "Touvet Volley-Ball",
            "Club Volley Ball Oullins",
            "Sain Bel Volley",
            "Douarnenez Volley Ball Club",
            "Pays d'Auray Volley-Ball",
            "La Rochelle Volley Ball",
            "Chatelaillon-Plage Volley-Ball",
            "Vertou Volley-Ball Loisirs",
            "Volley Saint Vitois",
            "Thorigne-Fouillard Volley-Ball",
            "JA Rennes Volley",
            "Volley Loisirs 21",
            "CM Floirac Volley",
            "Perigny Volley-Ball",
            "ASVEL Volley",
            "Voironnais Volley-Ball",
            "Volley Club Bastidien",
            "Avia Club Volley-Ball",
            "Volley Ball Ollioulais",
            "Volley Ball Villars",
            "Bousquet Bedarieux VB",
            "Volley Ball de Gignac",
            "Alliance Nord 77 VB",
            "ES Portes de la Bretagne VB",
            "Good Luck Fort de France Volley",
            "Etoile St Laurent Brest Volley",
            "UGS Lann Bihoue VB",
            "Olympique de Morieres VB",
            "Lille Université Club Volley",
            "Volley Beach-Ball Pont à Mousson",
            "Sport Joie Lille Volley",
            "AS Niçoise de Volley-Ball",
            "Dompierre sur Mer Volley-Ball",
            "CO St Fons Volley",
            "Entente St-Chamond Volley",
            "Six Fours Beach Volley",
            "Volley Loisirs de Bu",
            "Limeil-Brevannes Volley-Ball",
            "Cellois / Chesnay Volley-Ball",
            "Chaville-Sevres Volley-Ball",
            "Espace Volley Vernon/St Marcel",
            "Volley-Ball Club du Rhin",
            "Sport Club Selestat VB",
            "CS Bourgoin Jallieu Volley",
            "Sporting Club Paris Volley",
            "AS Roquefortoise de VB",
            "Saint-Medard Torce Volley-Ball",
            "Janze Corps-Nuds Volley-Ball",
            "Volley Club de la Cane",
            "Pays de Grasse Volley-Ball",
            "Volley la Tour du Pin",
            "2Gvb-Guilherand-Granges Volley-Ball",
            "Gazelec Beziers Maraussan Volley-Ball",
            "Imperium Garges Volley-Ball",
            "Combs Volley-Ball",
            "Pontault-Combault VB Club",
            "Volley-Ball Centre Mauges",
            "Volley Olympique du Puy",
            "Le Lion Volley-Ball",
            "ES VB Haute Goulaine",
            "Volley-Ball Luzien Cibourien",
            "Esn Volley Ball",
            "G.S.D. 78 Volley",
            "Association Castelneuvienne Volley Ball",
            "US Cagnes Volley-Ball",
            "Entente Choletaise Volley-Ball",
            "CA Volley Ball Jalioromain",
            "Volley Ball Club de Kani Be",
            "Volley-Ball St Maixentais",
            "US Albenassienne VB",
            "Cercle des Volleyeurs Nanceiens",
            "Club Volley-Ball Aptesien",
            "La Baule Volley-Ball",
            "As. les Joyeux Volleyeurs",
            "Marly-Le-Roi Volley-Ball",
            "Volley-Ball Club de Gournay",
            "Vallee de Chevreuse Volley-Ball",
            "Association Amandinoise de Volley-Ball",
            "Dunkerque Grand Littoral VB",
            "Entente Sportive Nanterre Volley-Ball",
            "Nantes Plaisir du Volley-Ball",
            "Etoile Sportive Champniers VB",
            "Volley Club de Saint-Saulve",
            "Entente Rhone Ouveze VB",
            "ASC Universite Montpellier 2 VB",
            "Ass Tampon Gecko Volley",
            "C.O.S Faches Thumesnil VB",
            "Beaumont Lavit Lomagne Volley-Ball",
            "AS Volley-Ball Loisir 57",
            "Patronage Laique 010 VB",
            "Cannes Aero Sports Volley-Ball",
            "Dinard Cote d'Emeraude Volley",
            "Pays de Salins Volley-Ball",
            "UGS Talence Gradignan Volley",
            "Castres Massaguel Volley Ball Club",
            "Amicale Laique Echirolles VB",
            "Gsd_Groupement Sportif Volley Club 17",
            "Union Salles Mios Volley-Ball",
            "AS Lacanau Section VB",
            "Sud Sainte-Baume Volley Club",
            "Union Sportive Castelgironnaise VB",
            "Pacy sur Eure Volley Ball",
            "Pays de Sommerviller Volley-Ball",
            "Tarbes Odos Pyrénées Volley-Ball",
            "Jurancon Chapelle Rousse VB",
            "Amicale Centre Hellemmes Volley-Ball",
            "Racing Club Epernay VB",
            "Volley Club Loisir de Chantonnay",
            "Volley-Ball Club de Mundolsheim",
            "Le Havre Estuaire Volley-Ball",
            "ASPTT Rouen Msa VB",
            "Amicale Laique Chambéry VB",
            "UGS Volley-Ball Roanne Riorges",
            "UGS Annemasse Volley Vallee Verte",
            "Volley-Ball Avesnes les Aubert",
            "Union Sportive Wissous VB",
            "Reveil Sportif Volley-Ball Tiffauges",
            "Entente Sportive Yerroise Volley-Ball",
            "Patronage Laïque Lorient Volley Ball",
            "CO Region Elbeuvienne Volley-Ball",
            "Fontaine le Comte Volley Ball",
            "Volley Ball Club le Haillan",
            "AS Nogentaise de Volley-Ball",
            "VB Passion Noyelles Sous Lens",
            "Portes de l'Essonne Volley-Ball",
            "ASB Rezé Volley-Ball Détente",
            "Buxy Volley Team",
            "Giromagny Volley-Ball",
            "Volley-Ball Riez Vie",
            "Esperance Morieres Volley-Ball",
            "LA Ferte Volley",
            "Volley Club de l'Authion",
            "Chatenoy Volley-Ball Club",
            "Volley-Ball Pays Viennois",
            "Association Volleyeurs Entre",
            "Volley Ball Club Limoges Landouge Loisirs",
            "Club VB Servon sur Vilaine",
            "Volley Olympique Juvisy/Athis Mons",
            "As. Chateau Gontier VB",
            "Louvigne de Bais Volley-Ball",
            "Villemomble Sports Section VB",
            "AVBA Association Volley Ball Agny ",
            "US Jeunesse Mitry VB",
            "Nort Athletic Club Volley",
            "Fraternelle St Charles VB",
            "Choisy le Roi Volley-Ball",
            "Volley Club Lieu Saint-Amand",
            "AC Boulogne Billancourt Volley",
            "CS Quincy Sous Senart Volley-Ball",
            "Sainte-Maxime Cogolin Volley",
            "Volley Club de Saint-Maximin",
            "VB Sennecey le Grand Canton",
            "Centurions17/ UGS Royan-Saintes VB",
            "Club Sportif Municipal Rosneen Volley-Ball",
            "AS Villeneuve d'Ascq Métropole Volley Ball",
            "US de Migne-Auxances Volley-Ball",
            "Association de Loisir Malville Volley-Ball",
            "Entente Volley du Pays de Liffre",
            "Amicale Laique Narassiguin Bras Panon VB",
            "CO de Sarralbe Section VB",
            "Loisir et Detente 64 VB",
            "Stella Sport Volley-Ball la Romagne",
            "Club Omnisports de Courcouronnes -Section VB",
            "Volley Ball du Luy de Bearn",
            "Groupement Sportif Departemental Nord de VB",
            "Association Sportive de Romille Volley",
            "Saint-Michel Sports Volley-Ball",
            "Pays de Fayence Volley-Ball",
            "AS Volleyeurs du Plessis Bouchard",
            "AS VB du Val d'Yerres",
            "Saint-Maurice Cotiere Volley",
            "UGS Chambray-Esvres Volley-Ball",
            "Volley Beaucaire Tarascon (Le) Gres",
            "Bouc-Bel-Air Volley-Ball",
            "Melun Val de Seine Volley-Ball",
            "As. Loisirs et Rencontres Volley",
            "CJF Fleury les Aubrais Volley",
            "UGS La Rochelle-Chatelaillon Plage VB",
            "LA Madeleine Volley-Ball et Vie Active",
            "AS Volley-Ball Taverny Saint-Leu",
            "UGS Volley Ball Cesson-Chantepie-Vern",
            "Amicale Villeneuve la Garenne VB",
            "Ent Proven Digne/Manosque VB",
            "Draguignan Union Club Var VB",
            "Pegomas Val de Siagne Volley-Ball",
            "AS Saint-Barthelemy d'Anjou VB",
            "AS Volley-Ball de Murs-Erigne",
            "COS Villers lès Nancy Volley",
            "Vesinet Stade St-Germanois VB",
            "Spcoc Volley-Ball la Colle Saint-Paul",
            "St Pol/Ternoise Section Volley",
            "AS Bourg-la-Reine Volley",
            "Rieux-Villers Saint-Paul Brenouille VB",
            "St Martin/St Aubin Volley",
            "ES Villiers sur Marne Volley",
            "Les Bleuets le Pertre VB",
            "Coudoux Velaux la Fare Volley-Ball",
            "Fs Val d'Europe Esbly Coupvray VB",
            "Volley-Ball de Milly la Forêt",
            "Entente Nord Ouest Anjou VB",
            "Aix Universite Club 13 Volley-Ball",
            "Groupement Sportif Departemental de l'Isere de VB",
            "US des Aigles Blanc de St Paul VB",
            "Orry-La-Ville, la Chapelle En Serval, Chantilly VB",
            "France",
            "AS St Sylvain d'Anjou",
            "Terville Florange Olympique Club",
            "Ass Sportive de Monaco",
            "Rennes",
            "JSA Bordeaux",
            "France Avenir 2024",
            "Belgium",
            "Turkey",
            "Russia",
            "Italy",
            "Bruyères",
            "Vénézuéla",
            "Orchies",
            "Macédoine",
            "Chypre",
            "Ukraine",
            "Roumanie",
            "Cuincy",
            "ASDEL",
            "Union Béarnaise",
            "VC Bellaing/Porte du Hainaut",
            "Entente Sportive du Canton de Pipriac",
            "Association Sportive Illacaise",
            "Rambervillers",
            "Cuinchy",
            "Barlin",
            "Azerbaijan",
            "Australie",
            "Suède",
            "Allemagne",
            "Bulgarie",
            "Finlande",
            "Kosovo",
            "Russie",
            "Vendegies",
            "Ronchin",
            "Marsauderie",
            "Cassav",
            "Loyat",
            "Harol",
            "Igney",
            "Tunisie",
            "Tourcoing",
            "Blendecques",
            "Canada",
            "Argentine",
            "Pays-Bas",
            "Autriche",
            "Slovénie",
            "Croatie",
            "Grèce",
            "Lettonie",
            "Turquie",
            "Montenegro",
            "Azerbaïdjan",
            "Mazingarbe",
            "USFEN",
            "VBLA",
            "ALCVB",
            "Concorde de Coueron",
            "Etoile d'Oignies",
            "Lissp Calais",
            "Anglet Olympique",
            "AS de Chantepie",
            "Grenoble V.Universite Club",
            "Bulgaria",
            "Chavelot",
            "Isbergues",
            "Quarouble",
            "Albanie",
            "Japon",
            "Iran",
            "États-Unis",
            "Brésil",
            "Belgique",
            "Estonie",
            "Biélorussie",
            "Espagne",
            "Portugal",
            "Israël",
            "Danemark",
            "Serbie",
            "Suisse",
            "Italie",
            "Norvège",
            "Hongrie",
            "Templeuve",
            "Marchiennes",
            "Malincourt",
            "Louvroil",
            "Assevent",
            "Thiant",
            "Laetitia",
            "EMINES",
            "Plumieux",
            "Ménéac",
            "Charmes",
            "Emerchicourt",
            "Bauvin",
            "Fenain",
            "Moldavie",
            "Chine",
            "Pologne",
            "Slovaquie",
            "Bosnie-Herzégovine",
            "Géorgie",
            "Longuenesse",
            "Menton",
            "ASPTT Laval",
            "AS SP Illzach Modenheim",
            "Union Sportive Guignen",
            "Etoile Sportive Arques",
            "Jeunes Sportifs de Beaufay",
            "Rennes Etudiants Club",
            "Télécom ParisTech",
            "Sigma Clermont",
            "ENSTA ParisTech",
            "Centrale Lyon",
            "Université Montpellier",
            "INP Toulouse",
            "Chimie ParisTech",
            "ESPCI Paris",
            "SupAgro Montpellier",
            "AS Casson",
            "Centrale Marseille",
            "IMT Atlantique",
            "Mines Nancy",
            "VBC Chamalières",
            "Union Sportive de Villejuif",
            "Cnm Charenton",
            "Agro ParisTech",
            "Australie",
            "",
            "Vieux Reng",
            "Mines Paris",
            "Cdj Villereau",
            "Valence Ace",
            "As.Sp.Cult.Ent.Equi. Nancy",
            "AS CHU",
            "Ste Pazanne",
            "Université Nimes",
            "Volero le Cannet",
            "Racing Club de Cannes",
            "AS Cesson Saint-Brieuc",
            "AS Boufféré",
            "Tremblay Athletique Club",
            "Proton SARATOV (RUS)",
            "Bully les Mines",
            "All Stars",
            "ENS Chimie Montpellier",
            "Fatum NYIREGYHAZA (HUN)",
            "Ribnica KRALJEVO (SRB)",
            "SK ANKARA (TUR)",
            "Dinamo BUCURESTI (ROU)",
            "VC Marcq-En-Baroeul Lille Métropole",
            "VBC Chalon sur Saone",
            "Aubigny en Artois",
            "Dompierre sur Helpe",
            "ENS Architecture Montpellier",
            "Montpellier Business School",
            "LP SALO (FIN)",
            "Kuzbass KEMEROVO (RUS)",
            "Minchanka MINSK (BLR)",
            "Olympiacos PIRAEUS (GRE)",
            "Omonoia NICOSIA (CYP)",
            "Stroitel MINSK (BLR)",
            "Halkbank ANKARA (TUR)",
            "Avenir Marpire Champeaux",
            "Club Loisirs Tourlaville",
            "V.B.C. la Possession",
            "SOLLENTUNA VC (SWE)",
            "VakifBank ISTANBUL (TUR)",
            "C.S.M. TARGOVISTE (ROU)",
            "Dinamo MOSCOW (RUS)",
            "Lokomotiv NOVOSIBIRSK (RUS)",
            "TRENTINO Itas (ITA)",
            "DRESDNER SC (GER)",
            "CAI TERUEL (ESP)",
            "Neftohimik BURGAS (BUL)",
            "Arkas IZMIR (TUR)",
            "THY ISTANBUL (TUR)",
            "Galatasaray Istanbul (TUR)",
            "Aulnoy lez Valenciennes",
            "Hebar PAZARDZHIK (BUL)",
            "LAUSANNE UC (SUI)",
            "OK NIS (SRB)",
            "TSV JONA (SUI)",
            "IMT Lille Douai",
            "Mladost ZAGREB (CRO)",
            "VfB FRIEDRICHSHAFEN (GER)",
            "JASTRZEBSKI Wegiel (POL)",
            "Knack ROESELARE (BEL)",
            "Projekt WARSZAWA (POL)",
            "ZOK UB (SRB)",
            "Levski SOFIA (BUL)",
            "Zenit KAZAN (RUS)",
            "Orion DOETINCHEM (NED)",
            "République Tchèque",
            "Pôle Espoirs de Strasbourg",
            "Saint Julien les Rosiers",
            "Mines Saint Etienne",
            "VC Greenyard MAASEIK (BEL)",
            "CV GRAN CANARIA (ESP)",
            "Fenerbahçe Opet ISTANBUL (TUR)",
            "M Tsangadoua Association",
            "Lokomotiv KALININGRAD Region (RUS)",
            "Developres RZESZÓW (POL)",
            "VC Maritza PLOVDIV (BUL)",
            "Amysoft Lycurgus GRONINGEN (NL)",
            "Draisma Dynamo APELDOORN (NED)",
            "AC PAOK THESSALONIKI (GRE)",
            "Decospan VT MENEN (BEL)",
            "Galatasaray HDI ISTANBUL (TUR)",
            "SWD powervolleys DUEREN (GER)",
            "Université Paul Valery",
            "VC Greenyard MAASEIK",
            "",
            "Mladi Radnik POZAREVAC (SRB)",
            "Le Val d'Ajol",
            "Pôle Espoirs de Nancy",
            "US Pont St Martin",
            "SC Prometey DNIPRO (UKR)",
            "Draisma Dynamo APELDOORN (NL)",
            "VK Lvi PRAHA (CZE)",
            "Amysoft Lycurgus GRONINGEN (NED)",
            "Asterix Avo BEVEREN (BEL)",
            "Vasas Óbuda BUDAPEST (HUN)",
            "AJM FC PORTO (POR)",
            "Sporting CP LISBOA (POR)",
            "Chênois GENEVE (SUI)",
            "IF ERGOTHÉRAPIE MONTPELLIER",
            "OK Nis NIS (SRB)",
            "Ecole Polytechnique Féminine Montpellier",
            "OK Merkur MARIBOR (SLO)",
            "Yokis",
            "CSM Arcada GALATI (ROM)",
            "Jihostroj ČESKÉ BUDĚJOVICE (CZE)",
            "Panathinaikos AC ATHENS (GRE)",
            "PGE Skra BELCHATOW (POL)",
            "IMT Mines Albi Carmaux",
            "ASPTT Perigueux",
            "Ziraat Bankasi ANKARA (TUR)",
            "Fenerbahçe HDI ISTANBUL (TUR)",
            "Igor Gorgonzola NOVARA (ITA)",
            "VK Dukla LIBEREC (CZE)",
            "VCA AMSTETTEN NÖ (AUT)",
            "TALLINN Technical University (EST)",
            "ČEZ KARLOVARSKO (CZE)",
            "DPD Legionovia LEGIONOWO (POL)",
            "ŁKS Commercecon ŁÓDŹ (POL)",
            "Cucine Lube CIVITANOVA (ITA)",
            "Sport LISBOA e Benfica (POR)",
            "Ferrière la Grande",
            "Groupement Sportif L.A.R.E.E.C.",
            "Zenit SAINT PETERSBURG (RUS)",
            "Ford Levoranta SASTAMALA (FIN)",
            "SSC Palmberg SCHWERIN (GER)",
            "Allianz MTV STUTTGART (GER)",
            "VK UP OLOMOUC (CZE)",
            "SF Paris Saint-Cloud",
            "Racing Club Arlesien",
            "Sir Sicoma Monini PERUGIA (ITA)",
            "VBC Saint Denis",
            "Vojvodina NS Seme NOVI SAD (SRB)",
            "Unet e-work BUSTO ARSIZIO (ITA)",
            "Foinikas SYROS Onex VC (GRE)",
            "Mairie Sportive",
            "Avenir Club Langan/La Chapelle",
            "AS du Departement de l'Allier",
            "Etoile de Morne A l'Eau",
            "IBM Montpellier",
            "Grupa Azoty Chemik POLICE (POL)",
            "Perkinelmer Leo Shoes MODENA (ITA)",
            "SK Zadruga AICH/DOB (AUT)",
            "A. Carraro Imoco CONEGLIANO (ITA)",
            "AO du Baillif",
            "Union Sportive de Goyave",
            "Entente Gisorsienne",
            "Racing Club de l'Ouest",
            "Dinamo-Ak Bars KAZAN (RUS)",
            "A.J. FONTE BASTARDO Azores (POR)",
            "Technische Hochschule Georg Agricola Bochum",
            "Aiglon du Lamentin",
            "S.T.A.F. Club",
            "VBC Flerien",
            "ASPTT Orleans",
            "LA Guideloise",
            "VBC Clermontais",
            "VDK Bank GENT Dames (BEL)",
            "ZOK Bimal-Jedinstvo BRČKO (BIH)",
            "Heol Santec",
            "CDV Guaguas LAS PALMAS (ESP)",
            "Asbam Montpellier",
            "VBC de Sainte-Suzanne",
            "A.O.C. des Jeunes de Ouangani",
            "M.J.C. Coursan",
            "Grupa Azoty KĘDZIERZYN-KOŹLE (POL)",
            "CSM Volei Alba BLAJ (ROM)",
            "VC Champs sur Marne",
            "Asperly",
            "UGS de Wissous et l'Elan de Chevilly Larue",
            "Union Sportive Civraisienne",
            "Gasny Omnisports 91",
            "AS Gondrexange Landange",
            "Union Sportive Vivonne",
            "Toulouse Athletic Club",
            "Crapahut",
            "ASPTT Lille",
            "Sporting Club Barbezilien",
            "A.Sp.Cult. Chevaliers de Rohan",
            "Union Sportive Dacquoise",
            "US Tournebride Hayange",
            "Foyer de Cambounet/Sor",
            "Biscarrosse Olympique",
            "CSA Chatellerault",
            "Sporting Club de Bernay",
            "Leers Omnisports",
            "Association Sportive Libourne",
            "Entente Senonaise",
            "Club Olympique Carbonnais",
            "V.B.C. Athletique Lexovien",
            "Association Sportive Epron",
            "Cercle Sportif de Bayeux",
            "VBC Kingersheim",
            "ASC Hausbergen",
            "Avant Garde Caennaise",
            "Club Omnisports de Pluvigner",
            "Mdpa Ruelisheim",
            "CSS CNE Lapi DEJ-SCM ZALAU (ROM)",
            "Sporting Club Coutançais",
            "Ent.Sp.Cult. Moulins",
            "Patronage Laique d'Argentan",
            "Foyer Laique de Lanester",
            "Sp.Loisirs Constantia",
            "MJC de Rodez",
            "Union Sportive Roubianaise",
            "Avenir St Georges",
            "Cl.Omni.St-Laurent du Maroni",
            "Ste Gymnastique Fraternelle",
            "AS Entretien Sailly",
            "VBC Parthenaisien",
            "M.J.C. Cavaillon",
            "AS Villeneuvoise",
            "US Athletique Toulougienne",
            "Union Sportive Valcourt",
            "Avignon",
            "Union Sportive Briotine",
            "Union Sportive Antrain",
            "Sport Athletique Rochefortais",
            "Etoile Sportive Conde Macou",
            "V.C.Jean Mace Hazebrouck",
            "Vb.Jeumont Maubeuge Val/Sambre",
            "SO Tourquennoise Stel",
            "Lattes ASPTT Montpellier V.A.C",
            "Olympique Club Cessonais",
            "Agglomeration Soissons VBC",
            "Amicale Laique Ledonienne",
            "Union Sportive Liffreenne",
            "Union Sportive d'Acigne",
            "Union Sportive Laille",
            "VBC Francheville Ouest Lyonnais",
            "ASPTT de Pau",
            "AS Taillis-St Christophe",
            "Amicale Sportive d'Evry",
            "Blain Omnisport",
            "Arsenal Club",
            "F.E.P.S. St Julien l'Ars",
            "Etoile Sportive de Buxerolles",
            "US Carcen-Ponson",
            "USM de Viroflay",
            "Acjcls Castelnauvienne",
            "Cabestany Olympique Culturel Omnisports",
            "Association Sportive Luynoise",
            "Loudeac Olympique Sport Club",
            "CSM Puteaux",
            "V Independant Club Combourg",
            "Postillon Olympique Longjumellois",
            "Etoile Sportive de Champniers Angouleme",
            "Centre des Loisirs d'Ottmarsheim",
            "AS Pouilly Metz",
            "Molsheim Olympique Club",
            "Omni Sports Chapellois",
            "Omnisports Club Helesmois",
            "CS de Sevres Anxaumont",
            "Etincelle Mayenne",
            "Paris Amicale Camou",
            "ASC Moulins les Metz",
            "MJC Dole",
            "Neuville Sports",
            "Club Olympique Guipellois",
            "Sporting Club de le Rheu",
            "AS de Geveze",
            "ASPTT Nice",
            "Ste Gymnastique la Wantzenau",
            "Club Sportif Ferte Mace",
            "AS Prep Olympique du Midi",
            "Ass Sportive de Gerardmer",
            "Olym Forezien St Cyprien",
            "Sporting Club Plaisance Touch",
            "L'Envolley 01",
            "Smash Club Buissard",
            "Amicale Laique de Toul",
            "Club Olympique Savigny",
            "A.S.C. Fumerolles",
            "Inter Club Tourcoing",
            "Esperance Sportive de Rouge",
            "Entente Sportive Craonnaise",
            "Etoile Sportive Lavalloise",
            "AO Ruillacoise",
            "Sports et Loisirs En Val Vienn",
            "Loudun Athletic Club",
            "Club Omnisports des Ulis",
            "Union Sportive Palaiseau",
            "Entente Sportive d'Hagondange",
            "AS St Leger Guebwiller",
            "Cercle Sportif Tricolore Saverne",
            "Sp.Reunis Elec.Gaz Mulhouse",
            "Club Athletique Evronnais",
            "I.A.F.V.O.",
            "Union Sportive du Jarnisy",
            "ASVB Yutz-Thionville",
            "En. Laique Albertville Ugine",
            "As. Sp. Cult. Dunois",
            "US Independante Tinteniac",
            "Amicale Laique Montagnarde",
            "As.Sp.Lois.Municipaux Cannes",
            "US Schweighouse sur Moder",
            "Fljep Lillers",
            "LA Cocarde",
            "Union Sportive Thouarsaise",
            "PLVPB Lyon 3 Villette",
            "Club Sportif de Decines",
            "Un.Sp.Vallee de la Gresse",
            "AC Citroen Cormelles",
            "Union Athletique de la Rochefoucauld",
            "Un.Sp.Litteraire Montjoly",
            "I.U.F.M. Sport",
            "Racin Beach",
            "Am Sp. Beaurains",
            "Stade Montluconnais",
            "ASC Dervalaise",
            "Union Sportive Chauvigny",
            "G.S.D. 92",
            "Club Sportif Mennecy",
            "CSM Eaubonne",
            "Entente SP Bournos Doumy",
            "Sports Réunis de Creutzwald",
            "Union Sportive Bainaise",
            "VBC du Canton de Castries",
            "VC Amicaliste d'Aulnoy",
            "Saint-Dizier",
            "Foyer Rural de Ger",
            "Epi de Grammond",
            "Patro. Laique Craponne",
            "Jeunesse Sport Coulaines",
            "ASPTT Besancon",
            "Sporting Club Nord Parisien",
            "LA Tour d'Auvergne Rennes",
            "Jeanne d'ARC de Bruz",
            "AS Residents Amis du Nord",
            "Strasbourg Universite Club",
            "Patronage Laique de Gradignan",
            "Lyon PESD",
            "Club Rhodia Vaise",
            "Entente Sportive de Bruges",
            "Union Sportive Guipry-Messac",
            "AS Racing Club du Morne des Esses",
            "Ste Gymnastique Alsatia Neuhof",
            "Entente Sportive Region Arpajonnaise",
            "VBC du Val de Munster",
            "Amicale Laique d'Andouille",
            "US Cheminots Amiens",
            "AS Champigny le Sec le Rochereau",
            "Union Sportive Novillars",
            "CS St-Ulrich Morschwiller",
            "Dieppe Universite Club",
            "AS SP Tricastine",
            "Union Sportive Ris Orangis",
            "Club Chevry",
            "Omnisports Frouard Pompey",
            "VC Hettange/Grande Soetrich",
            "AS Vallee de la Sauer",
            "MJC les Fleurs de Pau",
            "En SP Montgeronnaise",
            "V.B.C. Ripagerien",
            "Union Sport Rainneville",
            "Entente Vol.Beaucourt/Sochaux",
            "Jeanne d'ARC de Plechatel",
            "AV Garde Jd ARC Cauderan",
            "ASPTT Lannion",
            "Ass Spor Ambaresienne",
            "AS Martignas",
            "ASPTT Nantes",
            "Ass Sportive Dardilloise",
            "F.R.J.E.P. Charnas",
            "Ste Gymnastique d'Erstein",
            "ASPTT Cagnes sur Mer",
            "Lso Colombes",
            "M.J.C. Sant-Nicolas de Port",
            "Club Omnisports de Valbonne",
            "Association Sportive d'Herblay",
            "Velos Sports Fertois",
            "Vahl",
            "Amicale Laique St Priest",
            "AS Caluire et Cuire",
            "US St Georges Ancizes",
            "Entente V.B.C. Rillieux",
            "Club Sportif Brignolais",
            "Club Sportif et Culturel de Cayenne",
            "Amicale Cheminots Blainville",
            "AS Bruffiere Defontaine",
            "Courbevoie Sports",
            "Sables Etudiants Club",
            "Union Sportive Azerguoise",
            "Entente Sportive St Maurice",
            "Pole Espoirs Jean Perrin Lyon",
            "US Montsoult-Baillet-Maffliers",
            "Rueil Athletic Club",
            "Lambesc Sporting Club",
            "ASA Maisons Alfort",
            "As.Sportive St-Martinoise",
            "Olympiques Antibes Juan Pins",
            "AS Spatiale Aquitaine",
            "College Jean Rostand Quetigny",
            "A Pers SP Adm Paris Apsapvp",
            "As.Sp. Beaulieu S/Mer",
            "Sports et Loisirs de Marges",
            "Association Sportive Flavigny",
            "Union Sportive Echire /Saint Maixent",
            "VBC de la Cote Ouest",
            "Jeunesse Sannois St-Gratien",
            "US Fontenaysienne",
            "Vendée VBC Herbretais",
            "Ent Sport Meylan la Tronche",
            "Stade Clermontois",
            "UGS Riom-Cebazat",
            "Faisons CA Ensemble 92",
            "FJ Ille sur Tet",
            "Sainte-Genevieve Sports",
            "Entente Sportive Vitry",
            "AS Voltaire Chatenay",
            "Ass Amicale Sportive Fresnes",
            "Avant-Garde Municip Vesoul",
            "LA Vaillante Autun",
            "Etoile Sportive de Villeneuve",
            "UGS - Nogent-Asmp",
            "C Omnisports Chateau du Loir",
            "Amicale Laique de Saint-Colomban",
            "AS SP Ambrieres",
            "Chevigny Loisirs et Sports",
            "Alerte Sportive Montlouis",
            "Esperance de Sixt sur Aff",
            "Saint Avertin Sports",
            "Avant Garde St Denis",
            "Red Star Club Champigny",
            "As. Sportive et Culturelle Saint Donatien",
            "Avenir Club du Couesnon",
            "Sporting Club de l'Ouest",
            "Amicale du Personnel du Grand Nancy",
            "Alerte Saint-Jean",
            "CSM Sully sur Loire",
            "UO Demi-Lunoise Zacharie SB",
            "U.S.M. St-Denis En Val",
            "AS College Etoile Sainte-Croix Saint-Euverte",
            "AS St Medard En Jalles",
            "Amis de l'Instruction Laique",
            "AS Amicale Jeunesse Blesoise",
            "Union Sportive Noyal-Chatillon",
            "A.S.Chapelle Saint Aubin",
            "Etudiant Club Orléans",
            "Jeune Garde de l'Erdre Suce",
            "Cg San Martin Boulogne",
            "Union Athletique Valettoise",
            "AS Elan Chevilly-Larue",
            "Eveil Sportif Florentin",
            "Mareuil Sporting Club",
            "Club Sportif Mun Epinay",
            "Vblm 5 (Volley - Bad - Lyon Metropole 5)",
            "Club Spor. Fontaine les Dijon",
            "A.Volley Detente Maine/Loire",
            "Ent.Mulsanne St-Biez St-Ouen",
            "Entente Sportive St-Legeoise",
            "US Pont Ste Maxence V Ball",
            "Etoile Club Sp. Courneuvien",
            "Club Sportif de Gonesse",
            "Jeanne d'ARC de Rosny",
            "Association Saint-Maurice du Perreux",
            "Ass Sportive Fontenaysienne",
            "Club Espace Sportif de Sucy",
            "Racing Club d'Arras",
            "Union Sportive de St Andre",
            "SP Club Briard",
            "SMOC St-Jean de Braye",
            "US St-Cyr En Val Sec.Vb",
            "SS St Denis Mauves sur Loire",
            "AS St Pierre Andreze",
            "Angers Sports Lac de Maine",
            "Ent SP St Martin d'Heres",
            "AS de St Ouen l'Aumone",
            "Vie Au Grand Air de St Maur"
        ];

        $clubModel = new \App\Models\Club();

        $teams = $clubModel->find();
        $result = [];
        foreach ($clubs as $club)
        {
            $shortest = 999;
            foreach ($teams as $team)
            {
                // On enlève les mots Volley ball car ça ruine le matching
                $temp_club = str_replace("Volley-ball", "", $club);
                $temp_club = str_replace("Volley", "", $club);
                $temp_team = str_replace("Volley-ball", "", $team['name']);
                $temp_team = str_replace("Volley", "", $team['name']);

                // calcule la distance avec le mot mis en entrée et le mot courant
                $lev = levenshtein($temp_club, $temp_team);

                // cherche une correspondance exacte
                if ($lev == 0) {
                    // le mot le plus près est celui-ci (correspondance exacte)
                    $closest = $team['name'];
                    $shortest = 0;
                    break;
                }

                // Si la distance est plus petite que la prochaine distance trouvée
                // OU, si le prochain mot le plus près n'a pas encore été trouvé
                if ($lev <= $shortest) {
                    // définition du mot le plus près ainsi que la distance
                    $closest  = $team['name'];
                    $shortest = $lev;
                }
            }
            $result[$club] = array('value' => $closest);
        }
        echo '<pre>' , var_dump($result) , '</pre>';
    }
}
