INSERT INTO sport_analytics.division (div_name,div_code,`order`) VALUES
	 ('COUPE DE FRANCE FEMININE AMATEUR','COF ',NULL),
	 ('COUPE DE FRANCE FEMININE PRO','CNF ',NULL),
	 ('COUPE DE FRANCE MASCULINE AMATEUR','COM ',NULL),
	 ('COUPE DE FRANCE MASCULINE PRO','CNM ',NULL),
	 ('ELITE FEMININE','EFA ',NULL),
	 ('ELITE MASCULINE','EMA ',NULL),
	 ('CHAMPIONNAT PRE','PMA',NULL),
	 ('NATIONALE 2 FEMININE','2FA',NULL),
	 ('NATIONALE 2 MASCULINE','2MA',NULL),
	 ('NATIONALE 3 FEMININE POULE A','3FA ',NULL);
INSERT INTO sport_analytics.division (div_name,div_code,`order`) VALUES
	 ('NATIONALE 3 FEMININE POULE B','3FB ',NULL),
	 ('NATIONALE 3 FEMININE','3FC',NULL),
	 ('NATIONALE 3 FEMININE POULE D','3FD ',NULL),
	 ('NATIONALE 3 FEMININE POULE F','3FF ',NULL),
	 ('NATIONALE 3 FEMININE POULE G','3FG ',NULL),
	 ('NATIONALE 3 FEMININE POULE H','3FH ',NULL),
	 ('NATIONALE 3 MASCULINE','3MA',NULL),
	 ('NATIONALE 3 MASCULINE POULE E','3ME ',NULL),
	 ('NATIONALE 3 MASCULINE POULE F','3MF ',NULL),
	 ('NATIONALE 3 MASCULINE POULE G','3MG ',NULL);
INSERT INTO sport_analytics.division (div_name,div_code,`order`) VALUES
	 ('NATIONALE 3 MASCULINE POULE H','3MH ',NULL);